sudo: required

language: python

python:
    - "2.7"

services:
    - docker

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - exuberant-ctags
            - python-dev

install:
    - pip --no-cache-dir install \
        setuptools \
        numpy \
        matplotlib \
        contextlib2 \
        simplejson \
        pint \
        graphviz \
        git+https://github.com/MatthieuDartiailh/pyclibrary.git \
        coveralls
    - make -j NOCUDA=1
    - make install

    
script:
    - export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
    - cd test
    - ./travis.sh
env:
    global:
        - ENCRYPTION_LABEL: "886f75ecbd69"
        - COMMIT_AUTHOR_EMAIL: "travis@ledatelescope.github.io"

after_success:
    - coveralls
